### ISSUE TITLE
 change interval minutes 

### ISSUE THREAD

**Issue by FarisAlbalawi** [itsmeichigo/DateTimePicker#43] opened 2017-10-12 13:34 UTC
I can change interval minutes  to  30 minutes as selectable options in minutes table?

**Comment by dkalinai** [comment] 2017-11-03 19:15
Yes also wondering about this

**Comment by Huddie** [comment] 2017-11-04 23:50
Any answer?

**Comment by itsmeichigo** [comment] 2017-11-06 04:37
I have added a commit to make it possible to set minute interval. Due to the limit of UI, I decided to disable infinite scrolling if minute interval is other than 1 minute. Suggested values for intervals should be 1, 5, 10, 15 or 30 (added as an enum).
I'm still testing this commit, so if you're interested please help testing as well. I'll update the pod once I'm sure the commit works alright.

Thanks.

**Comment by Huddie** [comment] 2017-11-06 12:14
Can you add this issue as well. https://github.com/itsmeichigo/DateTimePicker/issues/38
As they are similar and go together wel

**Comment by dkalinai** [comment] 2017-11-06 12:56
Hi there @itsmeichigo its great news and appreciate the fast response to this. I will have this tested today and reply back with my findings. Least I can do for you.

**Comment by dkalinai** [comment] 2017-11-07 11:47
<img width="878" alt="screenshot 2017-11-07 13 45 03" src="https://user-images.githubusercontent.com/12793954/32492141-f2fd995c-c3c1-11e7-9d99-2fce0d41b98a.png">

The hour time doesnt start selected for some reason which makes ui quirky a bit. Other than that tested this out and it seems to work perfectly!

**Comment by dkalinai** [comment] 2017-11-07 11:47
thing to note that this seems to be related to 12h format only as in 24h format it doesnt reproduce.

**Comment by itsmeichigo** [comment] 2017-11-08 02:42
Thanks for helping out @dkalinai. The one you noticed above is a known issue, which is not related to this one and I'll make sure to get it fixed. I'll close this issue now.

**Closed as completed by itsmeichigo** 2017-11-08 02:42 UTC

**Comment by Huddie** [comment] 2017-11-09 01:58
@itsmeichigo So far it seems to be working well for me, is there any chance you could look into the issue I linked to above? Its a similar idea and works well with this
