### ISSUE TITLE
Suggestion: only allow user to select time after minDate

### ISSUE THREAD

**Issue by kevinxh** [itsmeichigo/DateTimePicker#15] opened 2016-11-17 05:02 UTC
If I set minimumDate to now, the picker still allows user to pick earlier time today.

It should restrict user to only pick time after now.

**Comment by itsmeichigo** [comment] 2016-11-17 06:48
Did you test with the latest code? If so, pls explain further the issue, because I couldn't reproduce the bug.

**Comment by JYNiMing** [comment] 2017-03-14 00:45
If you pick the first DateCollectionViewCell，click "DONE" then click "Pick", It will reproduce  the but: assertion failed: Selected date should be later or equal to minimum date.

**Comment by lzuccaro** [comment] 2017-03-25 10:59
Hi,
I'm experiencing the same issue. 

If I set the minimumDate, I can still select a time before the minimumDate. 
The date selection works properly, instead.

STEPS TO REPRODUCE:
1. Set the minimumDate (i.e. now).
2. Select a time before the minimumDate.
3. Click Done.

ACTUAL RESULT:
The picker returns a date+time before the minimumDate.

EXPECTED RESULT:
Prevent selecting time before the minimumDate

**Comment by itsmeichigo** [comment] 2017-03-30 06:41
Hi all,

Thanks for reporting the issue. I have pushed the fix for this in the latest commit, hope it helps.
Also, apologies for the late response. 

Cheers!

**Closed as completed by itsmeichigo** 2017-03-30 06:41 UTC

**Comment by lzuccaro** [comment] 2017-03-30 18:31
It works!
Thanks
