### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by treyholt** [itsmeichigo/DateTimePicker#73] opened 2018-08-21 21:28 UTC
For some reason scrolling for time doesn't seem to be working for me. I have to tap one at a time-if I scroll it pretty much just randomly selects a time.

**Comment by itsmeichigo** [comment] 2018-08-22 00:40
Have you updated the lib to the latest version? Also it’d be helpful if you could share how to reproduce the issue or a snippet of how you’re adding the picker.

**Comment by FStrout** [comment] 2018-09-04 15:17
I am having a similar issue. I use the control several times throughout my project. It works as expected when used as a DateTimePicker. When I use it in time-only mode, though it automatically resets/rebounds to the selectedDate whenever I try to set any component to another value. I'm not sure what the problem is. I set up is identical for both use cases with the exception of adding the isTimePickerOnly parameter to the time-only control.

I am using version 2.1.1.

**Comment by FStrout** [comment] 2018-09-04 15:31
My issue was related to the minimumDate and maximumDate parameters. I was setting minDate to currentDate minus 1 day and maxDate to currentDate. This prevented me from adjusting the components to any future setting. Maybe [treyholt](https://github.com/treyholt) is having a similar issue.

**Comment by treyholt** [comment] 2018-09-04 15:52
Interesting, I'm using it as a date Time Picker and here are my min, max variables as well as how I display the DTPicker:
let now = Date()
        let min = now.addingTimeInterval(60 * 5)
        let max = now.addingTimeInterval(60 * 60 * 24 * 14)
        let picker = DateTimePicker.show(selected: now.addingTimeInterval(60 * 60 * 24 * 4), minimumDate: min, maximumDate: max, in: self.view)

So even the min is in the future-maybe that is the problem.

**Comment by FStrout** [comment] 2018-09-04 22:14
I'm sure passing in a future date as the minDate wouldn't be a problem as long as the selectedDate is within the minDate-maxDate range. If that works then this issue should probably be closed. ;-)

**Comment by itsmeichigo** [comment] 2018-09-05 15:12
@FStrout @treyholt  That's correct - the selected date should not be earlier than the minimum date, otherwise the picker will not work properly. I will close this as it's not an issue.

**Closed as completed by itsmeichigo** 2018-09-05 15:12 UTC

**Comment by treyholt** [comment] 2018-09-05 16:17
Sorry no that was the code with it still not working, and I have tried a few different min dates (selected date is always between the min and max) and my scroll still snaps to a random time each scroll. Often it gets stuck between times as well (like in this picture). 
<img width="381" alt="screen shot 2018-09-05 at 8 52 39 am" src="https://user-images.githubusercontent.com/35981934/45105457-22a66980-b0e9-11e8-9369-36c90717b301.png">

Here's how I'm setting each piece up: 
    let now = Date()
        let min = now.addingTimeInterval(-0)
        let max = now.addingTimeInterval(60 * 60 * 24 * 14)

        let picker = DateTimePicker.show(selected: now.addingTimeInterval(60 * 60 * 24 * 4), minimumDate: min, maximumDate: max, in: self.view)

        picker.highlightColor = darkerRed
        picker.disableColor = picker.darkColor.withAlphaComponent(0.3)
        picker.dateFormat = "hh:mm MM/dd/YY"
        picker.titleLabelText = "Event Date"
        picker.frame.origin.y = (view.frame.height - picker.frame.height)
        picker.doneButtonColor = darkerRed
        picker.doneButtonTitle = "DONE"

        picker.todayButtonTitle = "Today"
        picker.updateDoneButtonState()
        picker.completionHandler = { date in
            guard let date = date else {
                return
            }
            self.current = date
            let formatter = DateFormatter()
            formatter.dateFormat = "h:mm a MM/dd/YY"

Also weirdly as you can tell from the picture, my doneButton doesn't show up for some reason.

**Comment by FStrout** [comment] 2018-09-05 16:26
So your minDate is == now. Your not actually subtracting anything from it so you probably won't be able to select anything in the past which would be a problem because you may want to go back before you go forward. (Change time from 14:45 to 15:15 you would have to set the hour first always - not very good UX).

**Comment by itsmeichigo** [comment] 2018-09-06 08:47
@treyholt I see from the syntax you pasted that you're using an older version - unfortunately I am unable to support older version. I tried with your min max value in the latest version 2.1.0 and found that it works fine. Please update the lib and let me know if that works for you.

**Comment by KrillioSokolov** [comment] 2018-10-13 16:20
@itsmeichigo First of all thanks for a great library.
swift 4.2, lib v. 2.1.2 and try in 2.1.0
I try set min = Date().addingTimeInterval(-0), and set picker.timeInterval = DateTimePicker.MinuteInterval.ten
Then I try use let min = now.addingTimeInterval(-60 * 60 * 24 * 14) and default minute step, and catch the same bag.
![img_3116](https://user-images.githubusercontent.com/23337273/46907548-d7b81700-cf1c-11e8-9d68-bde98d73f894.jpg)
