### ISSUE TITLE
How to show DateTimePicker in viewdidload?

### ISSUE THREAD

**Issue by 1tanvuong** [itsmeichigo/DateTimePicker#31] opened 2017-06-16 03:26 UTC
Hi guys! 
 UIApplication.shared.keyWindow?.addSubview(dateTimePicker)
How to show datetimepicker in UIview in viewdidload? Thanks!

**Comment by itsmeichigo** [comment] 2017-11-08 03:22
Duplicate of #9. Closing this issue.

**Closed as completed by itsmeichigo** 2017-11-08 03:22 UTC
Labels: duplicate, enhancement
