### ISSUE TITLE
[REQUEST] Please add an option to have custom time intervals say every 10 minutes for the time picker

### ISSUE THREAD

**Issue by dkalinai** [itsmeichigo/DateTimePicker#50] opened 2017-11-03 19:38 UTC
Please add an option to have custom time intervals say every 10 minutes for the time picker. Could nto figure out a good way to do this in the code myself unfortunately.

**Comment by itsmeichigo** [comment] 2017-11-06 02:21
Duplicate of #43

**Closed as completed by itsmeichigo** 2017-11-06 02:21 UTC
